### ISSUE TITLE
optimizaiton problem

### ISSUE THREAD

**Issue by chouqin3** [jianqingzheng/path_planning_for_FEVAR#1]
It's a great job. The matlab optimization function fminunc didn’t work. It said the function has achieved optimal state you set initially, just like the screenshot. Could you explain 

![image](https://user-images.githubusercontent.com/12481496/68524458-2099f500-0302-11ea-865c-511ae93cbf96.png)
When I close the gradient, objective function starts decreasing.
![image](https://user-images.githubusercontent.com/12481496/68524482-5dfe8280-0302-11ea-90ec-225da390d659.png)

**Comment by YanhaoZhang** [comment]
Hi @chouqin3, May I ask if you have fixed this issue? Thanks a lot.

**Comment by chouqin3** [comment]
No, provided code has some problems
